apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # default type, can use other types like making a certificate
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
